### PR TITLE
added Freshmen.net

### PR DESCRIPTION
**Pull request by acvigue**
Added an agent for Freshmen.net

### CODE REVIEW

**Comment by eyung71** [comment]
hi there... how do you download the Freshmen agent?

**Comment by acvigue** [comment]
I need to fix my fork of this repository and I will submit a pull request. Then, once the branches are merged, you will be able to download it. If you give me 30 minutes, I can put up a link for you.

**Comment by acvigue** [comment]
https://github.com/acvigue/plex-gay-metadata-agent

Download Freshmen.bundle
Update HelixStudios.bundle if you want model images for Helix

**Comment by paladin732** [comment]
Even with the helix fixes, still doesn't seem to match files directly downloaded from helix

**Comment by acvigue** [comment]
send the name of the file.

it should be <four digit scene id>.mp4 or HXM<dvd id>.mp4

if it still doesn't work. i'll add you to the updated repo.

------ Original Message ------

**Comment by lonnie-kelco-exa** [comment]
Examples directly downloaded from their website:
hx75_scene6_member_720p.mp4
hx99_scene1_member_720p.mp4
hx118_scene87_member_1080p.mp4

**Comment by paladin732** [comment]
Examples directly downloaded from their website:
hx75_scene6_member_720p.mp4
hx99_scene1_member_720p.mp4
hx118_scene87_member_1080p.mp4

**Comment by acvigue** [comment]
there's no logic to scrape metadata for those titles. There is no way to 
go from hxXX_sceneXX_member format to the XXXX.mp4 format.

Any future updates: https://github.com/acvigue/pgma <-- where it will be 
committed.

Helix's site doesn't have a URL for the script to scrape with that 
format.

You'll need to manually move to the XXXX.mp4 format

Look at the picture. (yes i used paint)

------ Original Message ------

**Comment by acvigue** [comment]
@eyung71 this repo seems dead, I forked and changes are here:

https://github.com/acvigue/pgma

**Comment by paladin732** [comment]
Thanks! I'll check the new repo and renaming them is easy enough, I'll do that.

**Comment by eyung71** [comment]
Thanks! I’ve followed that fork now. It would be great to resolve some of these niggling flaws and get this working. Let me see if my plugin is the latest and if anything has been improved in the last while.

**Comment by acvigue** [comment]
if you need any help renaming or using the new plugins, just open an issue there.

**Pull request closed without merging**
